In [ ]:
import pandas as pd
from numpy import array
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV

In [ ]:
from google.colab import files
uploads = files.upload()

Saving FeatureSelectionData.csv to FeatureSelectionData (1).csv


In [ ]:
data = pd.read_csv('FeatureSelectionData.csv')
data.head()

LOC  FUR          AMB PROX_SCH  ... WATER HK_SER       SIZE      PRICE
0     karen  yes       serene       no  ...   yes    yes  32.502345  31.707006
1  madaraka  yes  semi_serene      yes  ...    no     no  53.426804  68.777596
2     karen   no        noisy       no  ...   yes    yes  61.530358  62.562382
3     karen  yes  semi_serene       no  ...   yes    yes  47.475640  71.546632
4  buruburu   no  semi_serene       no  ...   yes    yes  59.813208  87.230925

[5 rows x 10 columns]

In [ ]:
nominal=['LOC','FUR','WATER','HK_SER']
ordinal=['AMB','PROX_SCH','PROX_ROAD','PROX_MALL']
target=['PRICE']
numerical=['SIZE']
categorical_data=data.select_dtypes(include=['object']).copy()
column_names=list(categorical_data.columns)

for feature in column_names:
  categorical_data[feature]=categorical_data[feature].astype('category')

for feature in ordinal:
  categorical_data[feature]= categorical_data[feature].cat.codes

categorical_data.head()

In [ ]:
data_copy=categorical_data.copy()
data_copy=pd.concat([pd.get_dummies(data_copy[nominal]),data_copy],axis=1)
#Onehot Encoding
#Problem -> Increases dimensionality
data_copy.drop(nominal,axis=1,inplace=True)
data_copy

new_data = pd.concat([data_copy,data[numerical],data[target]],axis=1)
new_data

LOC_buruburu  LOC_donholm  LOC_karen  ...  PROX_MALL       SIZE      PRICE
0              0            0          1  ...          1  32.502345  31.707006
1              0            0          0  ...          1  53.426804  68.777596
2              0            0          1  ...          1  61.530358  62.562382
3              0            0          1  ...          0  47.475640  71.546632
4              1            0          0  ...          1  59.813208  87.230925
5              0            1          0  ...          1  55.142188  78.211518
6              0            0          0  ...          0  52.211797  79.641973
7              0            0          0  ...          1  39.299567  59.171489
8              0            1          0  ...          0  48.105042  75.331242
9              0            0          1  ...          0  52.550014  71.300880
10             0            0          0  ...          0  45.419730  55.165677
11             0            0          0  ...          1  54.351635  82.478847
12             1            0          0  ...          0  44.164049  62.008923
13             0            0          1  ...          1  58.168471  75.392870

[14 rows x 17 columns]

In [ ]:
#Slicing the data
all_features = list(new_data.columns)
X = new_data.loc[:,all_features].values
y = new_data.loc[:,['PRICE']].values
y

array([[31.70700585],
       [68.77759598],
       [62.5623823 ],
       [71.54663223],
       [87.23092513],
       [78.21151827],
       [79.64197305],
       [59.17148932],
       [75.3312423 ],
       [71.30087989],
       [55.16567715],
       [82.47884676],
       [62.00892325],
       [75.39287043]])

In [ ]:
#Standardize X
X = StandardScaler().fit_transform(X)
X


array([[-0.40824829, -0.40824829,  1.34164079, -0.52223297, -0.40824829,
        -0.74535599,  0.74535599, -0.74535599,  0.74535599, -0.74535599,
         0.74535599,  0.89802651, -1.        ,  0.8660254 ,  0.8660254 ,
        -2.28520557, -2.72264663],
       [-0.40824829, -0.40824829, -0.74535599, -0.52223297,  2.44948974,
        -0.74535599,  0.74535599,  1.34164079, -1.34164079,  1.34164079,
        -1.34164079, -0.3592106 ,  1.        ,  0.8660254 ,  0.8660254 ,
         0.40190153,  0.0124287 ],
       [-0.40824829, -0.40824829,  1.34164079, -0.52223297, -0.40824829,
         1.34164079, -1.34164079, -0.74535599,  0.74535599, -0.74535599,
         0.74535599, -1.61644772, -1.        ,  0.8660254 ,  0.8660254 ,
         1.44255533, -0.44613097],
       [-0.40824829, -0.40824829,  1.34164079, -0.52223297, -0.40824829,
        -0.74535599,  0.74535599, -0.74535599,  0.74535599, -0.74535599,
         0.74535599, -0.3592106 , -1.        , -1.15470054, -1.15470054,
        -0.36234362

In [ ]:
#Principle components
pca=PCA(n_components=2)
pc_s=pca.fit_transform(X)
#Returning Principle Components
pca_data=pd.DataFrame(pc_s,columns=['PC1','PC2'])
final_data = pd.concat([pca_data,data[target]],axis=1)
final_data


PC1       PC2      PRICE
0  -0.949207  3.278921  31.707006
1  -2.297029 -1.273714  68.777596
2   2.682650  1.824363  62.562382
3  -0.140739  1.828107  71.546632
4   3.068501 -0.085945  87.230925
5   2.076079 -2.470752  78.211518
6   1.611633 -2.885043  79.641973
7  -1.611303  0.172500  59.171489
8  -1.869082 -0.727396  75.331242
9  -2.122194 -1.331538  71.300880
10 -1.137147  2.049996  55.165677
11  2.715757 -0.531495  82.478847
12 -2.698942 -1.589861  62.008923
13  0.671022  1.741858  75.392870

In [ ]:
pca.explained_variance_ratio_
#PC1 carries = 23.83% of the information
#PC2 carries = 19.26% of the information

array([0.23829154, 0.19268058])

In [ ]:
regressor= LassoCV()
X=final_data.drop("PRICE",1)
y= final_data['PRICE']
regressor.fit(X,y)

LassoCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
        max_iter=1000, n_alphas=100, n_jobs=None, normalize=False,
        positive=False, precompute='auto', random_state=None,
        selection='cyclic', tol=0.0001, verbose=False)